steps:
- name: gcr.io/cloud-builders/gsutil
  entrypoint: 'bash'
  id: 'cache_dep_upload'
  args:
  - '-c'
  - |
    echo ${PROJECT_ID}
    echo ${COMMIT_SHA}
    ls /workspace/bin
    echo gs://$PROJECT_ID-$_BUCKET/$REPO_NAME/$_MODEL_NAME/$COMMIT_SHA/$_MODEL_OBJ
    gsutil cp ./$_MODEL_OBJ gs://$PROJECT_ID-$_BUCKET/$REPO_NAME/$_MODEL_NAME/$COMMIT_SHA/$_MODEL_NAME

substitutions:
    _MODEL_OBJ: model.pkl
    _BUCKET: data-forward-test
    _MODEL_NAME: test_takemura
    _FRAMEWORK: SCIKIT_LEARN
