steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  id: 'push_tag'
  args:
  - '-c'
  - |
    pip install requests
    date
    echo v`env LANG="ja_JP.UTF-8" date +"%Y%m%d_%H%M%S"` > tag
    tag=`cat tag`
    echo $tag