steps:
- name: gcr.io/cloud-builders/gsutil
  entrypoint: 'bash'
  id: 'cache_dep_upload'
  args:
  - '-c'
  - |
    echo ${PROJECT_ID}
    echo ${COMMIT_SHA}
    ls /workspace/bin
    echo gs://$PROJECT_ID-$_BUCKET/$REPO_NAME/$_MODEL_NAME/$COMMIT_SHA/$_MODEL_OBJ
    gsutil cp ./$_MODEL_OBJ gs://$PROJECT_ID-$_BUCKET/$REPO_NAME/$_MODEL_NAME/$COMMIT_SHA/$_MODEL_OBJ

- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  id: 'deploy_model'
  args:
  - '-c'
  - |
    ver=`gcloud ml-engine versions list --model=$_MODEL_NAME --limit=1 --sort-by=~ | grep 'v'| sed -e "s/[^0-9]//g"`
    _VERSION_NAME=`v$((${ver} + 1))`
    gcloud beta ml-engine versions create $_VERSION_NAME \
      --model $_MODEL_NAME \
      --origin gs://$PROJECT_ID-$_BUCKET/$REPO_NAME/$_MODEL_NAME/$COMMIT_SHA/$_MODEL_OBJ \
      --runtime-version=$_RUNTIME \
      --framework $_FRAMEWORK \
      --python-version=$_PYTHONVER

substitutions:
    _MODEL_OBJ: model.pkl
    _BUCKET: data-forward-test
    _MODEL_NAME: test_model
    _FRAMEWORK: SCIKIT_LEARN
    _VERSION_NAME:
    _RUNTIME: '1.8'
    _PYTHONVER: '3.5'
