steps:
- name: gcr.io/cloud-builders/debian
  args:
  - echo $MODEL_OBJ; echo $_MODEL_NAME
  env:
  - 'MODEL_OBJ=model.pkl'
  - 'BUCKET=data-forward-test'

substitutions:
    _MODEL_NAME: test_takemura
    _FRAMEWORK: SCIKIT_LEARN