steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  id: 'push_tag'
  args:
  - '-c'
  - |
    pip install requests
    env LANG=ja_JP.UTF-8
    echo v`date +"%Y%m%d_%H%M%S"` > tag
    tag=`cat tag`
    echo $tag