steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  id: 'push_tag'
  args:
  - '-c'
  - |
    pip install requests
    echo v`env  TZ="UTC-9" date +"%Y%m%d_%H%M%S"` > tag
    tag=`cat tag`
    echo $tag
    python bin/create_pr.py $_GITHUB_API_TOKEN