steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  id: 'push_tag'
  args:
  - '-c'
  - |
    pip install requests
    echo $TZ
    export TZ=Asia/Tokyo
    echo $TZ
    date
    echo v`date +"%Y%m%d_%H%M%S"` > tag
    tag=`cat tag`
    echo $tag