steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  id: 'push_tag'
  env:
    - 'TZ="UTC-9"'
  args:
  - '-c'
  - |
    pip install requests
    echo v`date +"%Y%m%d_%H%M%S"` > tag
    tag=`cat tag`
    echo $tag
