<<<<<<< HEAD
---
=======
>>>>>>> test
defaults: &defaults
  working_directory: /src/github.com/mfkessai/examination_model
  docker:
    - image: google/cloud-sdk
      environment:
        CLOUDSDK_COMPUTE_ZONE: asia-northeast1-a
        TZ: Asia/Tokyo
<<<<<<< HEAD
version: 2
jobs:
=======
>>>>>>> test
  merge-preview:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: check cloudbuild.yaml syntax
          command: |
            echo

workflows:
  version: 2
  deploy:
    jobs:
<<<<<<< HEAD
      - merge-preview
=======
      - merge-preview
>>>>>>> test
